# Generated by Django 4.1.1 on 2022-10-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('experience', models.PositiveSmallIntegerField()),
                ('prototype', models.CharField(max_length=50)),
                ('overall_rating', models.PositiveSmallIntegerField()),
                ('potential', models.PositiveSmallIntegerField()),
                ('confidence', models.PositiveSmallIntegerField()),
                ('iq', models.PositiveSmallIntegerField()),
                ('is_free_agent', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=50)),
                ('speed', models.PositiveSmallIntegerField()),
                ('strength', models.PositiveSmallIntegerField()),
                ('agility', models.PositiveSmallIntegerField()),
                ('awareness', models.PositiveSmallIntegerField()),
                ('stamina', models.PositiveSmallIntegerField()),
                ('injury', models.PositiveSmallIntegerField()),
                ('run_off', models.PositiveSmallIntegerField()),
                ('pass_off', models.PositiveSmallIntegerField()),
                ('special_off', models.PositiveSmallIntegerField()),
                ('run_def', models.PositiveSmallIntegerField()),
                ('pass_def', models.PositiveSmallIntegerField()),
                ('special_def', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.league')),
                ('team', models.ManyToManyField(through='personnel.Contract', to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='personnel.player'),
        ),
        migrations.AddField(
            model_name='contract',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='teams.team'),
        ),
    ]
