# Generated by Django 4.1.1 on 2022-10-06 01:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 8, 29))),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('is_postseason', models.BooleanField(default=False)),
                ('is_divisional', models.BooleanField(default=False)),
                ('is_conference', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matchups', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matchups', to='teams.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='seasons.season')),
            ],
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('quarter', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('home_timeouts', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('away_timeouts', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('matchup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matchups.matchup')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_comps', models.SmallIntegerField(default=0)),
                ('passing_atts', models.SmallIntegerField(default=0)),
                ('passing_yds', models.SmallIntegerField(default=0)),
                ('passing_tds', models.SmallIntegerField(default=0)),
                ('passing_ints', models.SmallIntegerField(default=0)),
                ('passing_fds', models.SmallIntegerField(default=0)),
                ('times_sacked', models.SmallIntegerField(default=0)),
                ('receptions', models.SmallIntegerField(default=0)),
                ('receiving_targets', models.SmallIntegerField(default=0)),
                ('receiving_yds', models.SmallIntegerField(default=0)),
                ('receiving_tds', models.SmallIntegerField(default=0)),
                ('receiving_fds', models.SmallIntegerField(default=0)),
                ('rushing_atts', models.SmallIntegerField(default=0)),
                ('rushing_yds', models.SmallIntegerField(default=0)),
                ('rushing_tds', models.SmallIntegerField(default=0)),
                ('rushing_fds', models.SmallIntegerField(default=0)),
                ('fumbles_lost', models.SmallIntegerField(default=0)),
                ('def_ints', models.SmallIntegerField(default=0)),
                ('forced_fumbles', models.SmallIntegerField(default=0)),
                ('def_tds', models.SmallIntegerField(default=0)),
                ('def_return_yds', models.SmallIntegerField(default=0)),
                ('tackles', models.SmallIntegerField(default=0)),
                ('tackles_for_loss', models.SmallIntegerField(default=0)),
                ('qb_hits', models.SmallIntegerField(default=0)),
                ('sacks', models.SmallIntegerField(default=0)),
                ('safeties', models.SmallIntegerField(default=0)),
                ('field_goals', models.SmallIntegerField(default=0)),
                ('field_goal_atts', models.SmallIntegerField(default=0)),
                ('field_goal_long', models.SmallIntegerField(default=0)),
                ('extra_points', models.SmallIntegerField(default=0)),
                ('extra_point_atts', models.SmallIntegerField(default=0)),
                ('kickoffs', models.SmallIntegerField(default=0)),
                ('kickoff_yds', models.SmallIntegerField(default=0)),
                ('touchbacks', models.SmallIntegerField(default=0)),
                ('punts', models.SmallIntegerField(default=0)),
                ('punt_yds', models.SmallIntegerField(default=0)),
                ('punt_long', models.SmallIntegerField(default=0)),
                ('punt_blocks', models.SmallIntegerField(default=0)),
                ('punt_returns', models.SmallIntegerField(default=0)),
                ('punt_return_yds', models.SmallIntegerField(default=0)),
                ('punt_return_tds', models.SmallIntegerField(default=0)),
                ('punt_return_long', models.SmallIntegerField(default=0)),
                ('kick_returns', models.SmallIntegerField(default=0)),
                ('kick_return_yds', models.SmallIntegerField(default=0)),
                ('kick_return_tds', models.SmallIntegerField(default=0)),
                ('kick_return_long', models.SmallIntegerField(default=0)),
                ('penalties', models.SmallIntegerField(default=0)),
                ('penalty_yds', models.SmallIntegerField(default=0)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matchups.matchup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='personnel.player')),
            ],
        ),
    ]
