# Generated by Django 4.1.1 on 2022-10-06 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 29)),
        ),
    ]
