# Generated by Django 4.1.7 on 2023-02-28 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0002_alter_matchup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='is_conference',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='is_divisional',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='is_postseason',
        ),
        migrations.AlterField(
            model_name='matchup',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 29)),
        ),
    ]
