# Generated by Django 3.2.8 on 2021-10-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
