# Generated by Django 3.2.6 on 2021-08-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0021_delete_scoreboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.matchup')),
            ],
        ),
    ]
