# Generated by Django 4.1.1 on 2022-10-06 01:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2021, 8, 29))),
                ('current_date', models.DateField(default=datetime.date(2021, 8, 29))),
                ('phase', models.PositiveSmallIntegerField(choices=[(1, 'Re-signing'), (2, 'Free Agent Signing'), (3, 'Draft'), (4, 'Regular Season'), (5, 'Playoffs'), (6, 'Offseason')], default=4)),
                ('season_number', models.PositiveSmallIntegerField(default=1)),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.SmallIntegerField(default=0)),
                ('losses', models.SmallIntegerField(default=0)),
                ('ties', models.SmallIntegerField(default=0)),
                ('points_for', models.SmallIntegerField(default=0)),
                ('points_against', models.SmallIntegerField(default=0)),
                ('streak', models.SmallIntegerField(default=0)),
                ('home_wins', models.SmallIntegerField(default=0)),
                ('home_losses', models.SmallIntegerField(default=0)),
                ('home_ties', models.SmallIntegerField(default=0)),
                ('away_wins', models.SmallIntegerField(default=0)),
                ('away_losses', models.SmallIntegerField(default=0)),
                ('away_ties', models.SmallIntegerField(default=0)),
                ('div_wins', models.SmallIntegerField(default=0)),
                ('div_losses', models.SmallIntegerField(default=0)),
                ('div_ties', models.SmallIntegerField(default=0)),
                ('conf_wins', models.SmallIntegerField(default=0)),
                ('conf_losses', models.SmallIntegerField(default=0)),
                ('conf_ties', models.SmallIntegerField(default=0)),
                ('non_conf_wins', models.SmallIntegerField(default=0)),
                ('non_conf_losses', models.SmallIntegerField(default=0)),
                ('non_conf_ties', models.SmallIntegerField(default=0)),
                ('last_5_wins', models.SmallIntegerField(default=0)),
                ('last_5_losses', models.SmallIntegerField(default=0)),
                ('last_5_ties', models.SmallIntegerField(default=0)),
                ('division_ranking', models.PositiveSmallIntegerField(default=1)),
                ('conference_ranking', models.PositiveSmallIntegerField(default=1)),
                ('power_ranking', models.PositiveSmallIntegerField(default=1)),
                ('clinch_bye', models.BooleanField(default=False)),
                ('clinch_div', models.BooleanField(default=False)),
                ('clinch_berth', models.BooleanField(default=False)),
                ('clinch_none', models.BooleanField(default=False)),
                ('won_wild', models.BooleanField(default=False)),
                ('won_div', models.BooleanField(default=False)),
                ('won_conf', models.BooleanField(default=False)),
                ('won_champ', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_standings', to='seasons.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_standings', to='teams.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teamstanding',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='unique_team_standings_for_season'),
        ),
    ]
