# Generated by Django 4.1.1 on 2022-11-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_alter_season_current_date_alter_season_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstanding',
            name='clinch_berth',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='clinch_bye',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='clinch_div',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='clinch_none',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='won_champ',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='won_conf',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='won_div',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='won_wild',
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='clinched',
            field=models.CharField(blank=True, choices=[('BYE', 'Bye Week'), ('DIV', 'Division'), ('BTH', 'Playoff Berth'), ('OUT', 'Out of Contention')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='round_won',
            field=models.CharField(blank=True, choices=[('WLD', 'Wildcard'), ('DIV', 'Divisional'), ('CNF', 'Conference'), ('SHP', 'Championship')], max_length=3, null=True),
        ),
    ]
