# Generated by Django 4.1.7 on 2023-02-28 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_remove_teamstanding_clinch_berth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='current_date',
            field=models.DateField(default=datetime.date(2023, 8, 29)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 8, 29)),
        ),
    ]
