# Generated by Django 4.1.7 on 2023-03-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0004_alter_season_current_date_alter_season_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstanding',
            name='away_losses',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='away_ties',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='away_wins',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='conf_losses',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='conf_ties',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='conf_wins',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='div_losses',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='div_ties',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='div_wins',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='home_losses',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='home_ties',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='home_wins',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='last_5_losses',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='last_5_ties',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='last_5_wins',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='non_conf_losses',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='non_conf_ties',
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='non_conf_wins',
        ),
    ]
