# Generated by Django 4.1.1 on 2022-09-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='sites.site', verbose_name='site')),
                ('meta_description', models.CharField(default='Move the Chains is a web-based (American) football simulation game built with Python, Django, Bootstrap and Vanilla JS.', help_text='Default description used in SEO metadata', max_length=255)),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter handle with @ used in SEO metadata', max_length=255, null=True)),
                ('author', models.CharField(blank=True, help_text='Default author used in SEO metadata', max_length=255, null=True)),
                ('default_image', models.ImageField(blank=True, help_text='Default site image used in SEO metadata', null=True, upload_to='core/')),
                ('og_type', models.CharField(default='website', help_text='Default og:type for Open Graph protocol', max_length=255)),
                ('tc_type', models.CharField(default='summary', help_text='Default twitter:card type for Twitter Cards', max_length=255)),
                ('server_root', models.URLField(default='http://localhost:8000', help_text='Default server root used in SEO metadata')),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
    ]
