# Generated by Django 4.1.1 on 2022-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(default='Move the Chains is a web-based (American) football simulation game', help_text='Default description used in SEO metadata', max_length=255),
        ),
    ]
