# Generated by Django 4.2.3 on 2023-07-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='handle',
            field=models.SlugField(blank=True, unique=True, verbose_name='user handle'),
        ),
    ]
