# Generated by Django 3.2.8 on 2021-10-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20211003_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchup',
            old_name='is_preseason',
            new_name='is_postseason',
        ),
    ]
