# Generated by Django 3.2.8 on 2021-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20211007_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamranking',
            name='clinch_berth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='clinch_bye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='clinch_div',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='clinch_none',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='won_champ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='won_conf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='won_div',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='won_wild',
            field=models.BooleanField(default=False),
        ),
    ]
