# Generated by Django 3.2.8 on 2021-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_auto_20211009_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='is_conference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchup',
            name='is_divisional',
            field=models.BooleanField(default=False),
        ),
    ]
