# Generated by Django 3.2.6 on 2021-10-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
