# Generated by Django 3.2.6 on 2021-08-18 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('experience', models.PositiveSmallIntegerField()),
                ('prototype', models.CharField(max_length=100)),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('potential', models.DecimalField(decimal_places=2, max_digits=4)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=4)),
                ('iq', models.PositiveSmallIntegerField()),
                ('speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=4)),
                ('agility', models.DecimalField(decimal_places=2, max_digits=4)),
                ('awareness', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stamina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('injury', models.DecimalField(decimal_places=2, max_digits=4)),
                ('run_off', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pass_off', models.DecimalField(decimal_places=2, max_digits=4)),
                ('special_off', models.DecimalField(decimal_places=2, max_digits=4)),
                ('run_def', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pass_def', models.DecimalField(decimal_places=2, max_digits=4)),
                ('special_def', models.DecimalField(decimal_places=2, max_digits=4)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
