# Generated by Django 3.2.6 on 2021-08-19 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='QB', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='agility',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='awareness',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='injury',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pass_def',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='pass_off',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='prototype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='run_def',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='run_off',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='special_def',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='special_off',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='speed',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='stamina',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.team'),
        ),
    ]
