# Generated by Django 3.2.6 on 2021-08-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_team_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['location']},
        ),
        migrations.RenameField(
            model_name='league',
            old_name='commissioner_name',
            new_name='gm_name',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='commissioner',
            new_name='user',
        ),
    ]
