# Generated by Django 3.2.8 on 2021-10-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_rename_is_preseason_matchup_is_postseason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='matchup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
