# Generated by Django 3.2.8 on 2021-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20211006_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='duration',
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='league',
            name='gm_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playermatchstat',
            name='penalties',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermatchstat',
            name='penalty_yds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
