# Generated by Django 3.2.6 on 2021-08-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20210820_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='confidence',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='potential',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
