# Generated by Django 3.2.6 on 2021-08-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20210821_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
