# Generated by Django 3.2.6 on 2021-08-24 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_alter_player_overall_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='leagues.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='leagues.team')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2021, 8, 29))),
                ('duration', models.DurationField(default=datetime.timedelta(days=364))),
                ('phase', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_comps', models.IntegerField(default=0)),
                ('passing_atts', models.IntegerField(default=0)),
                ('passing_yds', models.IntegerField(default=0)),
                ('passing_tds', models.IntegerField(default=0)),
                ('passing_ints', models.IntegerField(default=0)),
                ('passing_fds', models.IntegerField(default=0)),
                ('times_sacked', models.IntegerField(default=0)),
                ('rushing_atts', models.IntegerField(default=0)),
                ('rushing_yds', models.IntegerField(default=0)),
                ('rushing_tds', models.IntegerField(default=0)),
                ('rushing_fds', models.IntegerField(default=0)),
                ('fumbles_lost', models.IntegerField(default=0)),
                ('def_ints', models.IntegerField(default=0)),
                ('forced_fumbles', models.IntegerField(default=0)),
                ('def_tds', models.IntegerField(default=0)),
                ('def_return_yds', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('tackles_for_loss', models.IntegerField(default=0)),
                ('qb_hits', models.IntegerField(default=0)),
                ('sacks', models.IntegerField(default=0)),
                ('safeties', models.IntegerField(default=0)),
                ('field_goals', models.IntegerField(default=0)),
                ('field_goal_atts', models.IntegerField(default=0)),
                ('field_goal_long', models.IntegerField(default=0)),
                ('extra_points', models.IntegerField(default=0)),
                ('extra_point_atts', models.IntegerField(default=0)),
                ('kickoffs', models.IntegerField(default=0)),
                ('kickoff_yds', models.IntegerField(default=0)),
                ('touchbacks', models.IntegerField(default=0)),
                ('punts', models.IntegerField(default=0)),
                ('punt_yds', models.IntegerField(default=0)),
                ('punt_long', models.IntegerField(default=0)),
                ('punt_blocks', models.IntegerField(default=0)),
                ('punt_returns', models.IntegerField(default=0)),
                ('punt_return_yds', models.IntegerField(default=0)),
                ('punt_return_tds', models.IntegerField(default=0)),
                ('punt_return_long', models.IntegerField(default=0)),
                ('kick_returns', models.IntegerField(default=0)),
                ('kick_return_yds', models.IntegerField(default=0)),
                ('kick_return_tds', models.IntegerField(default=0)),
                ('kick_return_long', models.IntegerField(default=0)),
                ('penalties', models.IntegerField(default=0)),
                ('penalty_yds', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='leagues.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='leagues.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='leagues.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='leagues.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.season'),
        ),
    ]
