# Generated by Django 3.2.6 on 2021-08-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_season_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
