# Generated by Django 3.2.6 on 2021-08-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_season_season_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('conference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='leagues.conference')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='leagues.league')),
            ],
        ),
    ]
