# Generated by Django 3.2.6 on 2021-08-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_auto_20210824_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='league',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='season',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='is_free_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='division',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='leagues.conference'),
        ),
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
