# Generated by Django 3.2.6 on 2021-08-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_auto_20210824_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='conference',
        ),
    ]
