# Generated by Django 3.2.6 on 2021-08-24 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_auto_20210824_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.team'),
        ),
    ]
