# Generated by Django 3.2.6 on 2021-08-25 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0017_alter_userteam_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='user',
        ),
        migrations.AddField(
            model_name='userteam',
            name='league',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
