# Generated by Django 3.2.6 on 2021-08-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_auto_20210824_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='leagues.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='leagues.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(through='leagues.Contract', to='leagues.Team'),
        ),
    ]
