# Generated by Django 3.2.6 on 2021-08-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0020_auto_20210825_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scoreboard',
        ),
    ]
