# Generated by Django 3.2.6 on 2021-08-25 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0021_delete_scoreboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='leagues.matchup'),
        ),
        migrations.AlterField(
            model_name='season',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.schedule'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.division'),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='league',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
