# Generated by Django 3.2.6 on 2021-08-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0022_auto_20210825_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='schedule',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='leagues.schedule'),
        ),
    ]
