# Generated by Django 3.2.6 on 2021-08-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_alter_season_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='schedule',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.schedule'),
        ),
    ]
