# Generated by Django 3.2.6 on 2021-08-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0026_rename_playerstats_playermatchstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstat',
            name='receiving_fds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='receiving_targets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='receiving_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='receiving_yds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='receptions',
            field=models.IntegerField(default=0),
        ),
    ]
