# Generated by Django 3.2.6 on 2021-08-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0027_auto_20210826_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Re-signing'), (2, 'Free Agent Signing'), (3, 'Draft'), (4, 'Training Camp'), (5, 'Preseason'), (6, 'Regular Season'), (7, 'Playoffs'), (8, 'Offseason')], default=6),
        ),
    ]
