# Generated by Django 3.2.6 on 2021-08-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0029_auto_20210829_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
