# Generated by Django 3.2.6 on 2021-08-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0030_season_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstanding',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
