# Generated by Django 3.2.6 on 2021-09-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0032_auto_20210927_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamranking',
            name='standing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='leagues.teamstanding'),
        ),
    ]
