# Generated by Django 3.2.6 on 2021-09-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0033_alter_teamranking_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
